// Brand to Models mapping for vehicle selection
export const brandModels: Record<string, string[]> = {
  Audi: ["A3", "A4", "A5", "A6", "A7", "A8", "Q3", "Q5", "Q7", "Q8", "TT", "R8", "e-tron"],
  Ford: [
    "F-150",
    "F-250",
    "F-350",
    "Mustang",
    "Explorer",
    "Escape",
    "Edge",
    "Expedition",
    "Ranger",
    "Bronco",
    "Maverick",
    "Transit",
  ],
  Chevrolet: [
    "Silverado 1500",
    "Silverado 2500",
    "Silverado 3500",
    "Tahoe",
    "Suburban",
    "Equinox",
    "Traverse",
    "Malibu",
    "Camaro",
    "Corvette",
    "Colorado",
  ],
  Porsche: ["911", "Cayenne", "Macan", "Panamera", "Taycan", "Boxster", "Cayman"],
  GMC: ["Sierra 1500", "Sierra 2500", "Sierra 3500", "Yukon", "Yukon XL", "Terrain", "Acadia", "Canyon"],
  Dodge: ["Ram 1500", "Ram 2500", "Ram 3500", "Charger", "Challenger", "Durango", "Journey"],
  GM: ["Various Models"],
  Toyota: [
    "Camry",
    "Corolla",
    "RAV4",
    "Highlander",
    "Tacoma",
    "Tundra",
    "4Runner",
    "Sienna",
    "Prius",
    "Avalon",
    "Sequoia",
  ],
  BMW: ["3 Series", "5 Series", "7 Series", "X1", "X3", "X5", "X7", "M3", "M5", "Z4", "i4", "iX"],
  "Mercedes-Benz": ["C-Class", "E-Class", "S-Class", "GLA", "GLB", "GLC", "GLE", "GLS", "A-Class", "CLA", "EQS"],
}
