export const parts = [
  "Engine",
  "Transmission",
  "Alternator",
  "Starter",
  "Battery",
  "Radiator",
  "Water Pump",
  "Fuel Pump",
  "Oil Pump",
  "Timing Belt",
  "Serpentine Belt",
  "Spark Plugs",
  "Ignition Coil",
  "Air Filter",
  "Oil Filter",
  "Fuel Filter",
  "Cabin Air Filter",
  "Brake Pads",
  "Brake Rotors",
  "Brake Calipers",
  "Brake Master Cylinder",
  "Brake Booster",
  "Shock Absorbers",
  "Struts",
  "Control Arms",
  "Ball Joints",
  "Tie Rod Ends",
  "Sway Bar Links",
  "CV Axles",
  "Wheel Bearings",
  "Steering Rack",
  "Power Steering Pump",
  "Headlights",
  "Tail Lights",
  "Fog Lights",
  "Turn Signal Lights",
  "Windshield",
  "Side Mirrors",
  "Door Handles",
  "Window Regulators",
  "Door Locks",
  "Hood",
  "Fenders",
  "Bumpers",
  "Grille",
  "Exhaust Manifold",
  "Catalytic Converter",
  "Muffler",
  "Exhaust Pipe",
  "Oxygen Sensor",
  "Mass Air Flow Sensor",
  "Throttle Body",
  "EGR Valve",
  "PCV Valve",
  "Thermostat",
  "Coolant Hoses",
  "Heater Core",
  "AC Compressor",
  "AC Condenser",
  "Blower Motor",
  "Evaporator",
  "Clutch Kit",
  "Flywheel",
  "Differential",
  "Transfer Case",
  "Driveshaft",
  "U-Joints",
  "Axle Shafts",
  "Wheel Hubs",
  "ABS Module",
  "ECU/ECM",
  "TCM",
  "BCM",
  "Instrument Cluster",
  "Airbag Module",
  "Seat Belts",
  "Seats",
  "Dashboard",
  "Center Console",
  "Glove Box",
  "Sun Visor",
  "Floor Mats",
  "Trunk Lid",
  "Tailgate",
  "Roof Rack",
  "Running Boards",
  "Tow Hitch",
  "Wiper Blades",
  "Wiper Motor",
  "Washer Pump",
  "Horn",
  "Antenna",
  "Speakers",
  "Amplifier",
  "Subwoofer",
]
