export const parts = [
  // Original parts list
  "Engine",
  "Transmission",
  "Alternator",
  "Starter",
  "Battery",
  "Radiator",
  "Water Pump",
  "Fuel Pump",
  "Oil Pump",
  "Timing Belt",
  "Serpentine Belt",
  "Spark Plugs",
  "Ignition Coil",
  "Air Filter",
  "Oil Filter",
  "Fuel Filter",
  "Cabin Air Filter",
  "Brake Pads",
  "Brake Rotors",
  "Brake Calipers",
  "Brake Master Cylinder",
  "Brake Booster",
  "Shock Absorbers",
  "Struts",
  "Control Arms",
  "Ball Joints",
  "Tie Rod Ends",
  "Sway Bar Links",
  "CV Axles",
  "Wheel Bearings",
  "Steering Rack",
  "Power Steering Pump",
  "Headlights",
  "Tail Lights",
  "Fog Lights",
  "Turn Signal Lights",
  "Windshield",
  "Side Mirrors",
  "Door Handles",
  "Window Regulators",
  "Door Locks",
  "Hood",
  "Fenders",
  "Bumpers",
  "Grille",
  "Exhaust Manifold",
  "Catalytic Converter",
  "Muffler",
  "Exhaust Pipe",
  "Oxygen Sensor",
  "Mass Air Flow Sensor",
  "Throttle Body",
  "EGR Valve",
  "PCV Valve",
  "Thermostat",
  "Coolant Hoses",
  "Heater Core",
  "AC Compressor",
  "AC Condenser",
  "Blower Motor",
  "Evaporator",
  "Clutch Kit",
  "Flywheel",
  "Differential",
  "Transfer Case",
  "Driveshaft",
  "U-Joints",
  "Axle Shafts",
  "Wheel Hubs",
  "ABS Module",
  "ECU/ECM",
  "TCM",
  "BCM",
  "Instrument Cluster",
  "Airbag Module",
  "Seat Belts",
  "Seats",
  "Dashboard",
  "Center Console",
  "Glove Box",
  "Sun Visor",
  "Floor Mats",
  "Trunk Lid",
  "Tailgate",
  "Roof Rack",
  "Running Boards",
  "Tow Hitch",
  "Wiper Blades",
  "Wiper Motor",
  "Washer Pump",
  "Horn",
  "Antenna",
  "Speakers",
  "Amplifier",
  "Subwoofer",
  
  // Additional parts from part-data folder
  "A Pillar",
  "A/C Compressor",
  "A/C Condenser",
  "A/C Evaporator",
  "Air Bag",
  "Air Ride Compressor",
  "Axle Shaft",
  "Back Door",
  "Back Glass",
  "Backup Camera",
  "Bumper Cover",
  "Console Front",
  "Console Rear",
  "Door",
  "Door Handle",
  "Door Handle In",
  "Door Mirror",
  "Drive Shaft Front",
  "Drive Shaft Rear",
  "Exhaust Assembly",
  "Fender",
  "Fog Lamp",
  "Fuse Box",
  "Glove Box",
  "Head Lights",
  "Headrest",
  "Mirror Rear View",
  "Radiator",
  "Seat Back",
  "Seat Belt",
  "Seat Front",
  "Signal Fog Lamp",
  "Speedometer",
  "Steering",
  "Steering Column",
  "Sun Visor",
  "Tail Light",
  "Thermostat Housing",
  "Transfer Case",
  "Window Glass Motor"
]
